feat(01-building-blocks): added work flow file

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -12,9 +12,9 @@ jobs:
     echo-goodbye:
         runs-on: ubuntu-latest
         steps:
-            - name: Failed Step
-              run: 
-                echo "I willl fail"
-                exit 1
-            - name: Echo Goodbye
-              run: echo "Goodbye, World!"
+          - name: Failed Step
+            run: 
+              echo "I willl fail"
+              exit 1
+          - name: Echo Goodbye
+            run: echo "Goodbye, World!"
